// run the playbook on jenkins server which is in public subnet
---
- hosts: Tomcat
  become: true
  tasks: 
    - name: example
        copy:
          src: /op/playbooks/wabapp/target/webapp.war
          dest: /opt/apache-tomcat-9.0.44/webapps
